name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install Selenium Testing Dependencies
      run: npm install
      working-directory: ./testing/hospiq-selenium-tests

    - name: Install Appium Testing Dependencies
      run: npm install
      working-directory: ./testing/appium-tests

    - name: Run Selenium E2E Tests
      run: npm test
      working-directory: ./testing/hospiq-selenium-tests
      env:
        CI: true

    - name: Run Appium Mobile E2E Tests
      run: npm test
      working-directory: ./testing/appium-tests
      env:
        CI: true
